language: node_js
node_js:
  - "10"
deploy:
  provider: npm
  email: dwaynecharrington@gmail.com
  api_key:
    secure: fOmYW0vSSkrJF0CFnv7P4yzdQYfsgnBJBM0qiV31a04AqjOrtf0J0YxMtLSSJMDnj6BiaJIuxrBqgT+1KBmavyXnoQfV7KrlmeACBwSn9bneiZZDz0OT7Lk+JN6cLZ7Qo4B+4FToFfx1CHkZ1AaAZJpXV8kPyVpQ1wK+Lk+m1wTZPecWdZpDyjmr+/DIlBebe6Nv6ldWl1q/3gNTmK+ha6syy5Lhugp1WaShd2EoskZxyd9sV0XADE8xVe2mVAP/nNzCM2P6wPRMB3uP36IHnWdi7FbkNVN1ZbLEMp6XkEn0lnFbrnT9P48PWREclTGstNwfsLF0AirKLVD0Qt8m9xshyx2wWl6Vjljc343SblwxgIytqnqob+pZtVrZ8Ir0DDDAk8VN8zpQX8w2L7wMywYsQcCzRU/eoo1eoZS3IMxo6zzLu5usO7FSxqUalYaJxn4gvoGKYr6/IlYJW5yWMDVdqbom41qTUnmD/dGWdBiicMn7CihE8a0BCMQzByXHFT5frtyMFKW4/YckuL1NYjd56e2YqY9f1HKpTZ1yYAtSI5VwzU744PmcKDu1+RHftM7uX13tYywhhKhBS7APDU2bN9iRoQkcxMeI38UhaJU8wRcv1C71NiinWe/JQbUkKEGmhCYfyhh9dWv9el7Eijeg2SMJdsJcogettjRNKlk=
  on:
    tags: true
    repo: Vheissu/steem-stream
